### DISCUSSION TITLE
Spring Boot application.yml Configuration for MicroStream Not Working As Expected

### DISCUSSION THREAD

**Discussion by Haribou** [microstream-one/microstream#501] [Q&A] [answered]
I am building a Spring Boot 2.7.2 application that contains a MicroStream embedded storage engine. The pom.xml of my application contains this dependency:

```
<dependency>
    <groupId>one.microstream</groupId>
   <artifactId>microstream-integrations-spring-boot</artifactId>
   <version>07.01.00-MS-GA</version>
</dependency>
```

My _application.yml_ Spring Boot configuration contains the following lines:

```
one.microstream:
   storage-directory: ./stateData
   backup-directory: ./stateDataBackup
   channel-count: 4
   housekeeping-interval: 10000
   entity-cache-timeout: 86400000
```

MicroStream works as expected within my Spring Boot application except that it completely ignores the MicroStream _application.yml_ configuration. It resorts to its default configuration and, for example, uses the _storage_ directory instead of the _stateData_ directory that I configured in _application.yml_. I don't understand why my MicroStream configuration is being ignored. Any ideas?

Thank you.
